import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Form from "@/components/Form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create a note!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/note-png/stickies-note-image-pixabay-18.png"
        />
      </Head>
      <main className="flex flex-col">
        <div className="flex flex-col items-start">
          <div className="flex flex-row justify-start w-full flex-wrap pt-8 md:pl-10 pl-4 items-center sm:w-1/2">
            <p className="md:text-5xl text-3xl">📝</p>
            <p className="font-semibold md:text-5xl text-3xl text-gray-200 md:pl-20 pl-0 md:-mt-12 mt-0">
              WANNA NOTE SOMETHING?...
            </p>
          </div>
          <div className="flex flex-col gap-3 w-full items-center pt-8">
           
            <Form />
          </div>
        </div>
      </main>
    </>
  );
}
