import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Form from "@/components/Form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create a note!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/note-png/stickies-note-image-pixabay-18.png"
        />
      </Head>
      <main className="flex flex-col min-h-screen">
        <div className="flex flex-col gap-3 w-full items-center">         
            <Form />
        </div>
      </main>
    </>
  );
}
